### ISSUE TITLE
Pseudo Dynamic Version of Obsidian-Colored-Sidebar

### ISSUE THREAD

**Issue by MisterCHOUN** [CyanVoxel/Obsidian-Colored-Sidebar#24]
Hello,

I'm here to share a version of this css code (Warning : I don't know a lot about css).

So I somehow managed to create a "pseudo" dynamic version of this project, you only need to add the color variables and this block :

```css
[data-path^="XX"],
.nav-folder:has([data-path^="XX"]),
.tree-item-children .nav-folder:has([data-path^="XX"]) {
  --prefix-color: var(--COLOR);
}
```

Of course : 
- replace the XX with a number or something else
- and replace the "COLOR"

So at the end you'll get something like this : 

```css
/*------------------------------------------------------------------------------
               Obsidian Colored Sidebar Items by CyanVoxel v2.0.0               

                   A colored sidebar CSS snippet inspired by
                   the "Coloured Folders" snippet by Lithou.

This snippet targets folders beginning with numbered prefixes, and applies full
color formatting based on the root colors listed below. The prefixes are both
customizable and extensible; feel free to change, add, and remove them based on
your own titles and vault structure! By default I have a range of 8+1 colors,
however I've provided some other common colors as a starting point for your own
customization. Just swap out the color variable names in the prefix groups.

------------------------------------------------------------------------------*/

:root {
  /* ================================ Colors ================================ */
  --red: #e22c3c;                /* Default Prefix: None */
  --red-orange: #e9404b;         /* Default Prefix: None */
  --orange: #ee6748;             /* Default Prefix: None */
  --amber: #fa9f50;              /* Default Prefix: None */
  --yellow: #ffd85e;             /* Default Prefix: None */
  --lime: #97e768;               /* Default Prefix: None */
  --mint: #52eea3;               /* Default Prefix: 00 */
  --cyan: #51e1e9;               /* Default Prefix: 01 */
  --cool-cyan: #43cfea;          /* Default Prefix: None */
  --light-blue: #54b6f8;         /* Default Prefix: 02 */
  --blue: #437cf3;               /* Default Prefix: 03 */
  --blue-violet: #6f51f4;        /* Default Prefix: None */
  --violet: #9446f8;             /* Default Prefix: 04 */
  --purple: #c952ed;             /* Default Prefix: 05 */
  --magenta: #e54f9b;            /* Default Prefix: 06 */
  --hot-red: #e3365e;            /* Default Prefix: 07 */
  --cool-gray: #515768;          /* Default Prefix: 99 */

  --default-text-color: #d0d0d0;
  --highlight: #fff;
  --shadow: #0b0c2c;

  --nav-item-weight-hover: bold;
}

/* Light Theme Specific Properties */
.theme-light {
  --contrast-color: var(--shadow);
  --default-text-color: var(--shadow);
  --bg-contrast-amount: 70%;
  --fg-contrast-amount: 30%;
  --medium-contrast-amount: 60%;
  --active-contrast-amount: 30%;

  /* Darker Versions of Bright Colors for Light Theme */
  --yellow: color-mix(in srgb, #ffd85e 90%, var(--shadow));
  --lime: color-mix(in srgb, #97e768 90%, var(--shadow));
  --mint: color-mix(in srgb, #52eea3 85%, var(--shadow));
  --cyan: color-mix(in srgb, #51e1e9 85%, var(--shadow));
  --cool-cyan: color-mix(in srgb, #43cfea 85%, var(--shadow));
  --light-blue: color-mix(in srgb, #54b6f8 90%, var(--shadow));
}

/* Dark Theme Specific Properties */
.theme-dark {
  --contrast-color: var(--highlight);
  --bg-contrast-amount: 15%;
  --fg-contrast-amount: 40%;
  --medium-contrast-amount: 20%;
  --active-contrast-amount: 10%;
}

/* All Folder Titles */
.nav-folder-title {
  /* --prefix-color: var(--default-text-color); */
  font-weight: bold;
  border-radius: 5px;
  
}

/* Narrower Padding on Desktop*/
/* If you want Obsidian default padding, just comment the whole section below */
@media only screen and (min-width: 768px) {
  .nav-file-title,
  .nav-folder-title {
    /* padding: 3px 5px 2px 4px !important; */
    padding-top: 3px !important;
    padding-right: 5px !important;
    padding-bottom: 2px !important;
    padding-left: 15px;
    --prefix-color: var(--default-text-color);
  }
}

/* Simplified styling for folders/files with data-path^="00" */

/* Template block
                                    [data-path^="XX"],
                    .nav-folder:has([data-path^="XX"]),
.tree-item-children .nav-folder:has([data-path^="XX"]) {
  --prefix-color: var(--COLOR);
}
*/

                                    [data-path^="00"],
                    .nav-folder:has([data-path^="00"]),
.tree-item-children .nav-folder:has([data-path^="00"]) {
  --prefix-color: var(--mint);
}

                                    [data-path^="01"],
                    .nav-folder:has([data-path^="01"]),
.tree-item-children .nav-folder:has([data-path^="01"]) {
  --prefix-color: var(--cyan);
}

                                    [data-path^="02"],
                    .nav-folder:has([data-path^="02"]),
.tree-item-children .nav-folder:has([data-path^="02"]) {
  --prefix-color: var(--light-blue);
}

                                    [data-path^="03"],
                    .nav-folder:has([data-path^="03"]),
.tree-item-children .nav-folder:has([data-path^="03"]) {
  --prefix-color: var(--blue);
}

                                    [data-path^="04"],
                    .nav-folder:has([data-path^="04"]),
.tree-item-children .nav-folder:has([data-path^="04"]) {
  --prefix-color: var(--violet);
}

                                    [data-path^="05"],
                    .nav-folder:has([data-path^="05"]),
.tree-item-children .nav-folder:has([data-path^="05"]) {
  --prefix-color: var(--purple);
}

                                    [data-path^="06"],
                    .nav-folder:has([data-path^="06"]),
.tree-item-children .nav-folder:has([data-path^="06"]) {
  --prefix-color: var(--magenta);
}

                                    [data-path^="07"],
                    .nav-folder:has([data-path^="07"]),
.tree-item-children .nav-folder:has([data-path^="07"]) {
  --prefix-color: var(--hot-red);
}

                                    [data-path^="08"],
                    .nav-folder:has([data-path^="08"]),
.tree-item-children .nav-folder:has([data-path^="08"]) {
  --prefix-color: var(--yellow);
}

                                    [data-path^="99"],
                    .nav-folder:has([data-path^="99"]),
.tree-item-children .nav-folder:has([data-path^="99"]) {
  --prefix-color: var(--cool-gray);
}

                                    [data-path^=""],
                    .nav-folder:has([data-path^=""]),
.tree-item-children .nav-folder:has([data-path^=""]) {
  --prefix-color: var(--default-text-color);
}

/* -------------------------------- Styling --------------------------------- */

/*
color: var(--prefix-color); -> colors the folders
--nav-item-background-hover -> color the rectangle hover the folder
--background-modifier-border-focus -> ???
--nav-collapse-icon-color -> colors the ">" folder icon
*/

.nav-folder-title {

  color: var(--prefix-color);
  --nav-item-color-hover: color-mix(
    in srgb,
    var(--prefix-color) var(--fg-contrast-amount),
    var(--contrast-color)
  );
  --nav-item-background-hover: color-mix(
    in srgb,
    /* var(--prefix-color) var(--bg-contrast-amount), */
    var(--prefix-color) 45%,
    transparent
  );
  --nav-collapse-icon-color: color-mix(
    in srgb,
    var(--prefix-color) 100%,
    transparent
  );
  --nav-indentation-guide-color: color-mix(
    in srgb,
    var(--prefix-color) 100%,
    transparent
  );
}

/* FOR FILES
color: color-mix -> colors the files' titles
--nav-item-background-hover -> color the rectangle hover the file
--background-modifier-border-focus -> ???
--nav-item-background-active -> color the rectangle background of a file when you're using it
*/


.nav-file-title  {
  color: color-mix(
    in srgb,
    var(--prefix-color) 60%,
    var(--default-text-color)
  );
  --nav-item-background-hover: color-mix(
    in srgb,
    var(--prefix-color) 45%,
    transparent
  );
  /* --background-modifier-border-focus: color-mix(
    in srgb,
    var(--prefix-color) 100%,
    transparent
  ); */
  --nav-item-background-active: color-mix(
    in srgb,
    var(--prefix-color) 25%,
    transparent
  );
}

/* Default styling for all folders 
Because the variable color was not HERITED or something like that
*/
.nav-folder,
.tree-item-children .nav-folder {
  --prefix-color: var(--default-text-color); /* Fallback value */
  --nav-indentation-guide-color: color-mix(
    in srgb,
    var(--prefix-color) 100%,
    transparent
  );
}
```

And the results should look like this : 

![Image](https://github.com/user-attachments/assets/46141de8-4f60-4e99-a573-937be35bf423)

![Image](https://github.com/user-attachments/assets/10ae59aa-50f3-4264-a870-c89e064fecf8)

End

PS : You might want to modify the highlight and color for the light mode ...
